services:
  web:
    build: .
    container_name: rails_api_web
    working_dir: /app
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: meu_primeiro_rails_api_development
    command: bash -c "rm -f tmp/pids/server.pid && tail -f /dev/null"

  db:
    image: postgres:16
    container_name: rails_api_db
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meu_primeiro_rails_api_development
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  bundle_cache:
