default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "123456") %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "meu_primeiro_rails_api_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_TEST_NAME", "meu_primeiro_rails_api_test") %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", "app_production") %>
    username: <%= ENV.fetch("DATABASE_USER", "app") %>
    password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("DATABASE_CACHE_NAME", "app_production_cache") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("DATABASE_QUEUE_NAME", "app_production_queue") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("DATABASE_CABLE_NAME", "app_production_cable") %>
    migrations_paths: db/cable_migrate
